Repository yomorun/yomo, pull requests merged in 2020-12, with the labels that each got.

#57 update yomo-codec to v1.0.0
  go.mod
  go.sum
  pkg/yomo/run.go
Labels: feat

#73 Update Makefile to support `make build`
  Makefile
Labels: doc

#82 feat/plugin: use GOPATH to solve plugin issue
  Makefile
  README.md
  internal/cmd/init.go
  internal/serverless/build.go
Labels: feat/cli

#83 docs: update README for `yomo init`
  README.md
Labels: doc

#84 docs: README readability
  README.md
  docs/private_repo.md
  docs/tutorial-1.png
  docs/tutorial-2.png
  docs/tutorial-3.png
Labels: doc
