Repository yomorun/yomo, pull requests merged in 2023-11, with the labels that each got.

#678 fix(zipper): improve error description when auth
  core/server.go
Labels: feat/zipper, feat/log

#674 fix: return ErrConnClosed if write frame failed
  pkg/listener/quic/quic.go
Labels: bug

#679 fix(zipper): update unit test for improve error description when auth
  core/client_test.go
Labels: bug

#681 fix: client always reconnect unless conn be closed
  core/client.go
  core/frame/frame.go
  core/server.go
  pkg/listener/quic/quic.go
  pkg/listener/quic/quic_test.go
Labels: feat/log

#680 feat(cli): yomo init with test file
  cli/cli.go
  cli/init.go
  cli/serverless/golang/template.go
  cli/serverless/golang/templates/init_test.tmpl
  serverless/mock/mock_context.go
Labels: feat/cli
