Repository yomorun/yomo, pull requests merged in 2023-09, with the labels that each got.

#604 fix: github action release rename from zip to tar.gz
  .github/workflows/release.yaml
Labels: ci

#607 fix(zipper): If the name of the SFN is not configured in the Zipper config file, reject the SFN.
  core/stream_group.go
  sfn_test.go
Labels: feat/zipper

#605 feat(sfn): add wait api
  core/client.go
  example/0-basic/sfn/main.go
  example/3-multi-sfn/stream-fn-1/app.go
  example/3-multi-sfn/stream-fn-2/app.go
  example/3-multi-sfn/stream-fn-3/app.go
  example/3-multi-sfn/stream-fn-4/app.go
  example/4-cascading-zipper/sfn/sfn_echo.go
  example/5-backflow/sfn-1/main.go
  example/5-backflow/sfn-2/main.go
  example/6-mesh/stream-fn-db/app.go
  example/6-mesh/stream-fn/app.go
  sfn.go
Labels: feat/serverless

#609 docs(prscd): add support for `go get yomo.run/prscd`
  docs/.gitignore
  docs/next.config.mjs
  docs/public/prscd.html
Labels: doc

#612 feat: transmitting data is broadcast across zippers by default
  core/client_test.go
  core/metadata.go
  core/metadata_test.go
  core/server.go
  docs/pages/docs/api/source.mdx
  example/4-cascading-zipper/README.md
  example/4-cascading-zipper/source/source.go
  example/6-mesh/source/main.go
  example/9-cli/source/main.go
  example/README.md
  pkg/config/config_test.go
  source.go
  source_test.go
  test/config.yaml
Labels: feat/stream
