Repository yomorun/yomo, pull requests merged in 2024-03, with the labels that each got.

#742 feat: add Google Gemini API provider (#2)
  cli/serve.go
  example/10-ai/sfn-timezone-calculator/main.go
  pkg/bridge/ai/provider/gemini/model_converter.go
  pkg/bridge/ai/provider/gemini/model_request.go
  pkg/bridge/ai/provider/gemini/model_response.go
  pkg/bridge/ai/provider/gemini/model_test.go
  pkg/bridge/ai/provider/gemini/provider.go
  pkg/bridge/ai/provider/gemini/provider_test.go
Labels: feat

#763 docs: fix code indents in README
  README.md
Labels: doc

#766 fix: cli support windows
  cli/test.go
  go.mod
  go.sum
Labels: bug

#768 fix: ai service race
  pkg/bridge/ai/api_server.go
  pkg/bridge/ai/service.go
Labels: bug

#772 refactor: cli test-prompt subcommand
  cli/test.go
  example/10-ai/llm-sfn-get-ip-and-latency/go.mod
  example/10-ai/llm-sfn-get-ip-and-latency/go.sum
  example/10-ai/llm-sfn-get-ip-and-latency/main.go
  pkg/bridge/ai/service.go
Labels: feat/cli
